# Generated by Django 2.2 on 2019-04-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0003_auto_20190414_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='em',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo.category'),
        ),
    ]
