# Generated by Django 2.2 on 2019-04-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0006_auto_20190414_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='admin_name',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='video',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo.category'),
        ),
    ]
