# Generated by Django 2.2 on 2019-04-14 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mo', '0009_auto_20190414_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videoT',
            new_name='sitevideo',
        ),
        migrations.AlterField(
            model_name='sitevideo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo.category'),
        ),
    ]
