# Generated by Django 2.2 on 2019-04-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0010_auto_20190414_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='sitevideo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo.sitecategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
