# Generated by Django 2.2 on 2019-04-14 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mo', '0011_auto_20190414_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sitecategory',
            new_name='scategory',
        ),
        migrations.RenameModel(
            old_name='sitevideo',
            new_name='svideo',
        ),
        migrations.RenameField(
            model_name='scategory',
            old_name='name',
            new_name='nam',
        ),
        migrations.RenameField(
            model_name='svideo',
            old_name='cat',
            new_name='cate',
        ),
    ]
