# Generated by Django 2.2 on 2019-04-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0013_auto_20190414_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='cat',
            new_name='cate',
        ),
    ]
