# Generated by Django 2.2 on 2019-04-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0015_auto_20190414_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cate',
            new_name='category',
        ),
    ]
