# Generated by Django 2.2 on 2019-04-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0016_auto_20190414_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
