# Generated by Django 2.2 on 2019-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0017_auto_20190424_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(null=True)),
            ],
        ),
    ]
