# Generated by Django 2.2 on 2019-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0018_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mo/static/SportsTube/search images/')),
            ],
        ),
    ]
