# Generated by Django 2.2 on 2019-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0019_search_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_images',
            name='img',
            field=models.ImageField(upload_to='mo/static/SportsTube/search_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
