# Generated by Django 2.2 on 2019-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0020_auto_20190427_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
